# Generated by Django 4.2.5 on 2023-09-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sap', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DocXml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('doc_number', models.PositiveIntegerField(unique=True)),
                ('doc_type', models.PositiveSmallIntegerField()),
                ('date_exp', models.DateField()),
                ('date_issue', models.DateField()),
                ('total', models.FloatField()),
                ('iva', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProvType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.PositiveBigIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('prov_sap', models.CharField(max_length=10)),
                ('cta_sap', models.PositiveIntegerField(blank=True, null=True)),
                ('prov_type', models.CharField(choices=[('Proveedor', 'Proveedor'), ('Financiera', 'Financiera')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.SmallIntegerField(default=1)),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('amount', models.FloatField()),
                ('doc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.docxml')),
            ],
        ),
        migrations.AddField(
            model_name='docxml',
            name='rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.provtype'),
        ),
    ]
