# Generated by Django 4.2.5 on 2023-09-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provtype',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
