# Generated by Django 4.0.5 on 2023-09-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_alter_provtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='iva_ammount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='iva_type',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
