# Generated by Django 4.0.5 on 2023-09-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_item_iva_ammount_item_iva_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='iva_type',
            field=models.CharField(default=22, max_length=10),
        ),
    ]
