# Generated by Django 4.0.5 on 2023-09-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_alter_item_iva_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.CharField(blank=True, max_length=20, null=True)),
                ('date_until', models.CharField(blank=True, max_length=20, null=True)),
                ('account', models.CharField(blank=True, max_length=50, null=True)),
                ('doc_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Model.docxml')),
            ],
        ),
    ]
