# Generated by Django 4.0.5 on 2024-02-02 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0005_addata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sap', models.CharField(default='G_100', max_length=10)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='docxml',
            old_name='iva',
            new_name='iva_basic',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='amount',
            new_name='amount_total',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='iva_ammount',
            new_name='iva_amount',
        ),
        migrations.AddField(
            model_name='addata',
            name='cons_lect',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='addata',
            name='lect_act',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='addata',
            name='lect_ant',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='docxml',
            name='cod_doc',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docxml',
            name='currency',
            field=models.CharField(default='UYU', max_length=10),
        ),
        migrations.AddField(
            model_name='docxml',
            name='iva_min',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docxml',
            name='sobre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='cod',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='desc_porc',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provtype',
            name='control_account',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='addata',
            name='account',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='addata',
            name='date_from',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addata',
            name='date_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='iva_type',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='provtype',
            name='norma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Model.norma'),
        ),
    ]
