# Generated by Django 4.2.5 on 2024-02-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0006_norma_rename_iva_docxml_iva_basic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docxml',
            name='id_doc',
            field=models.CharField(default=1228108, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
